// CONSTANTS
const PI = Math.PI
const PI_4 = PI / 4
const DEGREES_TO_RADIANS = PI / 180
const RADIANS_TO_DEGREES = 180 / PI
const TILE_SIZE = 512
// Average circumference (40075 km equatorial, 40007 km meridional)
const EARTH_CIRCUMFERENCE = 40.03e6
const FOV = 0.6435011087932844 * RADIANS_TO_DEGREES
const NEAR = 10
const FAR = EARTH_CIRCUMFERENCE
export {
  PI,
  PI_4,
  FOV,
  NEAR,
  FAR,
  DEGREES_TO_RADIANS,
  RADIANS_TO_DEGREES,
  TILE_SIZE,
  EARTH_CIRCUMFERENCE
}
